# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00261052da75a7c4a4db8cf370263b4844a4b1aad497f070ac77305549c755cdc54be36b927b93b5cdaf7e0d0e4661fc332b494db6226b024cc6c18af801b4b3

test:
  secret_key_base: 75a3d8720d3126fe6024e5c810f530878da6863f8901ecb9df56b6597d7b423d74ac6c54a4aa109805ab2e375f9d47556fa9df9c5f61970a596c7197ae644adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
